services:
  client:
    build:
      context: ./client/
    image: kramer-client:prod
    container_name: kramer-client
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app
    env_file: ./client/.env
    networks:
      - kramer

  backend:
    build:
      context: ./api/
    image: kramer-api:prod
    container_name: kramer-api
    ports:
      - 3170:3170
    volumes:
      - ./api/:/app
    env_file: ./api/.env
    networks: 
      - kramer
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: kramer-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kramer
    volumes:
      - new-db:/var/lib/mysql
    networks:
      - kramer

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kramer-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - kramer
    depends_on:
      - mysql

volumes:
  new-db:

networks:
  kramer:
